### ISSUE TITLE
Use  "setlocal"  instead of "set"

### ISSUE THREAD

**Issue by vayn** [mikewest/vimroom#10]
I tried to split a new window and edited it after I closed VimRoom, I just got a warning told me the window wasn't modifiable.

Use  `setlocal noma`  instead of `set noma` could solve this problem.

p.s. I did too many changes in my fork, so I think I cannot pull request directly...

**Comment by mikewest** [comment]
Thanks, this is fixed. I'll take a look at some of the other changes you've made... any in particular that you think are worth bringing back into my repo?
