### ISSUE TITLE
Usability tweaks

### ISSUE THREAD

**Issue by eater** [mikewest/vimroom#15]
It would be great to have the option to automatically keep the current colorscheme's background color -- is that possible?

Also an option to keep the status bar visible for those of us who want it.

A luxury feature would be if the sidebar width and positioning was automatically recalculated if the user resizes the gvim window.

**Comment by markstos** [comment]
I recommend this be converted into three separate issues, either a clear title.

**Comment by eater** [comment]
My patch addresses issue 1 here. Closing.
