### ISSUE TITLE
Errors with navigation key mappings

### ISSUE THREAD

**Issue by redcapital** [mikewest/vimroom#2]
If you have these mappings already defined in `~/.vimrc`:

```
nnoremap j gj
nnoremap k gk
```

When executing `VimroomToggle` Vim complains about already defined mappings.

```
Error detected while processing function <SNR>73_VimroomToggle:
line 66:
E227: mapping already exists for <80>ku
line 67:
E227: mapping already exists for <80>kd
line 68:
E227: mapping already exists for k
line 69:
E227: mapping already exists for j
```

and then everything works ok. I tried to comment out lines defining mappings in plugin code and then errors disappeared.

Linux
Vim 7.3
Vimroom latest cloned from github (last commit date: January 02, 2011)

**Comment by mikewest** [comment]
Sorry I haven't looked at this yet. I'll take a look tonight. It should be pretty simple to fix.
