### ISSUE TITLE
help file / doc

### ISSUE THREAD

**Issue by millermedeiros** [mikewest/vimroom#21]
it would be great if the plugin contained a `doc/vimroom.txt` with all the available options + how the plugin works (basically what is available [on the site](http://projects.mikewest.org/vimroom/)), just so we could do `:help vimroom` instead of opening the browser to check the settings, etc..

just found out about the plugin and really enjoining it so far. thx a lot!

**Comment by sotte** [comment]
take a look at 9516860405e8073bba5eb9886cda4bb4d5b41714

**Comment by millermedeiros** [comment]
sweet!
