### ISSUE TITLE
Has issues with vim-powerline

### ISSUE THREAD

**Issue by evantravers** [mikewest/vimroom#22]
When using this plugin: https://github.com/Lokaltog/vim-powerline

you get weird escaping going on when you invoke VimRoom.

before vimroom:
http://cl.ly/2W2H1C1t372J1G0c3C1L

after vimroom:
http://cl.ly/3V2n1J0D1j2K3V3B352C

I wish I was more of a vim pro to give a solution rather than just presenting a problem… it would appear that it has to do with some escaping of characters. I'd be content if the statusbar just hid during vim room mode. I dunno.

**Comment by sotte** [comment]
I don't experience the same problem. My powerline looks fine.

I normally turn it off 

```
set statusline=0
```

 when I'm in vimroom.

**Comment by adrusi** [comment]
I have this problem

**Comment by Lokaltog** [comment]
This is caused by vim's `fillchars` setting. I'm not using vimroom so I don't know if vimroom actually touches this setting, but you could try to add this to an "after" plugin and see if that solves the problem:

```
set fillchars+=stl:\ stlnc:\  " Caution: trailing space
```

**Comment by neoascetic** [comment]
[There](https://github.com/mikewest/vimroom/issues/34) is another workaround, set sidebar height to 0: `let g:vimroom_sidebar_height=0`. It solves problem for me.

**Comment by evantravers** [comment]
I use goyo.vim now. (https://github.com/junegunn/goyo.vim)
