### ISSUE TITLE
Doesn't support solarize color scheme background

### ISSUE THREAD

**Issue by alexkravets** [mikewest/vimroom#7]
I'm running vim in Mac OS Lion terminal, here how it looks:

http://cl.ly/2A3U3H3e1y3z10003C0s

**Comment by mikewest** [comment]
I don't know of a way to programatically read the background color, but I assume it must exist.

While I dig around for that, I'd suggest setting `g:vimroom_background` in your `.vimrc`. Vimroom uses that color to style the splits it opens at the margins: setting it to Solarized's background color should address the issue while I work on a real fix.

**Comment by trapd00r** [comment]
Xterm compatible terminals can make use of OSC 11, like so:

```
> printf "\e]11;?\007"; xxd
^[]11;rgb:1212/1212/1212^G
```

**Comment by vayn** [comment]
I added below in my vimrc to change background color in different environment:

``` VimL
if has('gui_running')
  let g:vimroom_background = '#002b36'
else
  let g:vimroom_background = 8
endif
```

The colors come from dark solarized colorscheme, you can change them to light style colors.

And change color settings in VimRoom:

``` VimL
if has('gui_running')
  exec('hi LineNr guibg=' . g:vimroom_background)
  exec('hi VertSplit guibg=' . g:vimroom_background . ' guifg=' . g:vimroom_background)
  exec('hi NonText guibg=' . g:vimroom_background . ' guifg=' . g:vimroom_background)
  exec('hi StatusLine guibg=' . g:vimroom_background . ' guifg=' . g:vimroom_background)
  exec('hi StatusLineNC guibg=' . g:vimroom_background . ' guifg=' . g:vimroom_background)
else
  exec('hi LineNr ctermbg=' . g:vimroom_background)
  exec('hi VertSplit ctermbg=' . g:vimroom_background . ' ctermfg=' . g:vimroom_background)
  exec('hi NonText ctermbg=' . g:vimroom_background . ' ctermfg=' . g:vimroom_background)
  exec('hi StatusLine ctermbg=' . g:vimroom_background . ' ctermfg=' . g:vimroom_background)
  exec('hi StatusLineNC ctermbg=' . g:vimroom_background . ' ctermfg=' . g:vimroom_background)
endif

```

[![Snapshot](http://f.cl.ly/items/2Z1h2h1E0o140F2i322t/2011-10-09-203409_scrot.png)](http://cl.ly/251J0j042E290v0e0b32)

**Comment by jonasb** [comment]
Using `bg` for terminals works more reliably. I think in the end different settings are needed for GUI and cterm. I've done that in my fork, see [pull request 11](https://github.com/mikewest/vimroom/pull/11).

**Comment by mikewest** [comment]
I've pulled in Jonas' commits. Can you test those locally, Alex?

Note that this changes `g:vimroom_background` into two variables: `g:vimroom_guibackground` which is used when a GUI is running, and `g:vimroom_ctermbackground`, which is used on the terminal.  That would change Vayn's example to:

```
let g:vimroom_guibackground = '#002b36'
let g:vimroom_ctermbackground = 8
```

and the color settings in Vimroom have been completely reworked.

**Comment by alexkravets** [comment]
Thank you guys! Now it looks to be working correct:

vimroom enabled: http://cl.ly/210f1F1d1T1r1K1V311u
no vimroom: http://cl.ly/0X0k2o2V1P2p043k0L1T

So looks to be working now.
Thanks again.
Alex

**Comment by toomey8** [comment]
Would it be possible for someone to post about how to get this working for terminal based solarized dark 

with 
set term=screen-256color 

thanks!

**Comment by toomey8** [comment]
Turns out I had to set iterm contrast to low and then it worked.
