### ISSUE TITLE
Toggling vimroom Kills Splits

### ISSUE THREAD

**Issue by rdegges** [mikewest/vimroom#8]
Hi there,

First of all--vimroom is awesome. Been using it all day, and couldn't be more pleased!

The issue I've noticed is that:
1. I have a couple split windows open.
2. I use :VimroomToggle to enable vimroom.
3. vimroom works great!
4. I'm done with vimroom, so I run :VimroomToggle again.
5. All my splits are gone.

Would be nice if you could store the state of vim as it was beforehand, so the splits get restored. Thanks!

**Comment by mikewest** [comment]
Right, I never considered using Vimroom from inside a split. It calls `:only` to toggle off, which results in the behaviou you're seeing.

I'll look into adjusting that to explicitly kill off the splits th plugin creates instead of blindly wiping them all.

**Comment by mikewest** [comment]
Can you check to see if the fix I've just committed works for you? If so, I'll wrap it up into a v0.8 release today. :)

**Comment by vayn** [comment]
If I don't use height padding, it'll close my current window. So I change the code above to:

``` VimL
if g:vimroom_sidebar_height
  wincmd j
  close
  wincmd k
  close
endif
if g:vimroom_min_sidebar_width
  wincmd l
  close
  wincmd h
  close
endif
```

**Comment by mikewest** [comment]
Ah, right. I forgot that was an option. Thanks Vayn! I'll commit that in a moment.

**Comment by rdegges** [comment]
So, it looks like the new behavior for me is:
1. I open up two windows (in splits).
2. I activate vimroom in one split and I get a vim-room style writing space in the split I ran it in, while the other split says open as normal.
3. I deactivate vimroom in my split, and vimroom closes that split (doesn't keep my content open), but keeps the other split (the one that never used vimroom at all) open.

So in the end, I've got:

1 open split window with nothing in it
1 open split window with my (untouched) content in it

I think it would be nice to have the behavior work like:

If a user has multiple splits open and enables vimroom, then:
- Close all other splits except the one that the user is currently in.
- Activate vimroom using the entire terminal (for maximum effect).

And when vimroom is de-activated, then:
- If the user had multiple splits open before activating vimroom, re-open them.

That way, you get a really nice 'fluid' experience. So for instance, you could be working on:
- Code in one split.
- Tests in another.
- And your blog in the third.

And when you want to focus purely on 'writing' the blog post, you could switch to that split, toggle vimroom ON, and have it immediately fill up the entire terminal so you can focus on writing in a nice way. Then, when you're done writing (or need to reference your other splits), just toggle vimroom OFF, and immediately return to your original setup.

What do ya think? Is that even possible?

<3

**Comment by vayn** [comment]
Hi @rdegges, you could try [ZoomWin](http://www.vim.org/scripts/script.php?script_id=508), it works very well with VimRoom.

**Comment by rdegges** [comment]
Hey @Vayn, that's actually perfect--that does exactly what I want ^^ Thanks! Never seen that before :)

**Comment by vayn** [comment]
On Tue, Oct 11, 2011 at 5:10 AM, Randall Degges <
reply@reply.github.com>wrote:

> Hey @Vayn, that's actually perfect--that does exactly what I want ^^
> Thanks! Never seen that before :)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mikewest/vimroom/issues/8#issuecomment-2352310

You are welcome :)

---

Don't Panic. 不要惊慌。
