### ISSUE TITLE
Disabling line numbers when user uses relativenumber

### ISSUE THREAD

**Issue by vayn** [mikewest/vimroom#9]
If I use relativenumber, I can't use `set nonumber` directly to disable line numbers.

I must set line number to normal number and then disable it:

``` VimL
set number
set nonumber
```

**Comment by mikewest** [comment]
Huh. I've never actually seen `relativenumber` before. Helpful!

I'll add support next to the regular `number`. I need to touch that again anyway to properly restore state when toggling vimroom off.

**Comment by mikewest** [comment]
Can you pull the latest `master` branch and let me know if that fixes the issue for you? Thanks!

**Comment by vayn** [comment]
Nice work! Thank you.
